import { Noto_Sans_Lao_Looped } from "next/font/google";
import "./globals.css";
import Header from "./_conponents/Header";
import Footer from "./_conponents/footer";
import { Toaster } from "sonner";

const noto_Sans_Lao_Looped = Noto_Sans_Lao_Looped({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-display',
});

export const metadata = {
  title: "HOSPITAL+ | Setthathirath hospital",
  description: "Generated by tock",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={noto_Sans_Lao_Looped.variable} >
      <body className="flex flex-col w-full" >
      <Header/>
      <main className="w-full md:px-20 font-display"> 
      {children}</main>
      <Toaster/>
        <footer><Footer/></footer>
         </body>
        
    </html>
  );
}
